[project]
name = "paper-ilamb-uncertainty"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ilamb3",
    "intake-esgf>=2026.6.4",
]

[tool.uv.sources]
ilamb3 = { git = "https://github.com/rubisco-sfa/ilamb3", rev = "main" }
